language: php

sudo: true

addons:
  firefox: "47.0.1"
  postgresql: "9.5"
  apt:
    packages:

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

dist: trusty

matrix:
  include:
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE NODEJS=14
    - php: 7.1
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_35_STABLE NODEJS=14
    - php: 7.1
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_36_STABLE
    - php: 7.1
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_37_STABLE NODEJS=14
    - php: 7.1
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_38_STABLE NODEJS=14
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_39_STABLE NODEJS=14
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=master NODEJS=14
    - php: 7.2
      env: DB=pgsql  MOODLE_BRANCH=master NODEJS=14

before_install:
  - phpenv config-rm xdebug.ini
  - if [ "$NODEJS" = 14 ]; then
      nvm install 14.0.0;
      nvm use 14.0.0;
    else
      nvm install 8.9;
      nvm use 8.9;
    fi
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
